import type { jsPDF } from "jspdf";
import iconSvgRaw from "../assets/Subtract.svg?raw";

type WarningHandler = (message: string) => void;

export interface BrandingAssets {
  logoDataUrl: string;
  logoSvgText?: string;
  logoPngDataUrl?: string;
  fallbackReason?: string;
}

export interface ExportHeaderOptions {
  appName?: string;
  appVersion: string;
  exportedAt?: Date;
  projectName?: string;
  title?: string;
}

interface FormattedHeader {
  titleLeft: string;
  titleCenter: string;
  titleRight: string;
  subline: string;
}

interface PdfHeaderTarget {
  kind: "pdf";
  doc: jsPDF;
  pageWidth: number;
  margin: number;
}

interface CanvasHeaderTarget {
  kind: "canvas";
  ctx: CanvasRenderingContext2D;
  canvasWidth: number;
  marginX: number;
}

interface PdfFooterTarget {
  kind: "pdf";
  doc: jsPDF;
  pageWidth: number;
  pageHeight: number;
  margin: number;
  pageLabel?: string;
}

interface CanvasFooterTarget {
  kind: "canvas";
  ctx: CanvasRenderingContext2D;
  canvasWidth: number;
  canvasHeight: number;
  marginX: number;
  pageLabel?: string;
}

let cachedAssetsPromise: Promise<BrandingAssets> | null = null;

function escapeSvgForDataUrl(input: string): string {
  return encodeURIComponent(input)
    .replace(/%0A/g, "")
    .replace(/%20/g, " ")
    .replace(/%3D/g, "=")
    .replace(/%3A/g, ":")
    .replace(/%2F/g, "/");
}

function warnWithFallback(reason: string, onWarning?: WarningHandler) {
  console.warn(`[Wrap Preview] branding logo fallback used: ${reason}`);
  onWarning?.(`Export branding fallback used: ${reason}`);
}

async function rasterizeSvgToPng(svgDataUrl: string, size: number): Promise<string> {
  const img = new Image();
  img.decoding = "sync";
  img.src = svgDataUrl;
  await new Promise<void>((resolve, reject) => {
    img.onload = () => resolve();
    img.onerror = () => reject(new Error("SVG image load failed"));
  });
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d");
  if (!ctx) {
    throw new Error("Canvas context unavailable");
  }
  ctx.clearRect(0, 0, size, size);
  ctx.drawImage(img, 0, 0, size, size);
  return canvas.toDataURL("image/png");
}

export async function getBrandingAssets(onWarning?: WarningHandler): Promise<BrandingAssets> {
  if (!cachedAssetsPromise) {
    cachedAssetsPromise = (async () => {
      const svgDataUrl = `data:image/svg+xml;charset=utf-8,${escapeSvgForDataUrl(iconSvgRaw)}`;
      try {
        const pngDataUrl = await rasterizeSvgToPng(svgDataUrl, 160);
        return {
          logoDataUrl: pngDataUrl,
          logoPngDataUrl: pngDataUrl,
          logoSvgText: iconSvgRaw,
        };
      } catch (error) {
        const reason = error instanceof Error ? error.message : "unknown rasterization failure";
        return {
          logoDataUrl: svgDataUrl,
          logoSvgText: iconSvgRaw,
          fallbackReason: reason,
        };
      }
    })();
  }
  const assets = await cachedAssetsPromise;
  if (assets.fallbackReason) {
    warnWithFallback(assets.fallbackReason, onWarning);
  }
  return assets;
}

export function getSmartCopyLine(appName: string, version: string): string {
  return `Generated by ${appName} (v${version}). Offline media control for creatives — review, verify, and deliver with confidence.`;
}

export function formatExportHeader(opts: ExportHeaderOptions): FormattedHeader {
  const appName = opts.appName || "Wrap Preview";
  const exportedAt = opts.exportedAt || new Date();
  return {
    titleLeft: `${appName} v${opts.appVersion}`,
    titleCenter: opts.projectName || opts.title || appName,
    titleRight: exportedAt.toLocaleString("en-GB"),
    subline: getSmartCopyLine(appName, opts.appVersion),
  };
}

async function drawLogoOnCanvas(
  ctx: CanvasRenderingContext2D,
  assets: BrandingAssets,
  x: number,
  y: number,
  size: number,
  onWarning?: WarningHandler
) {
  try {
    const img = new Image();
    img.src = assets.logoPngDataUrl || assets.logoDataUrl;
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject(new Error("Canvas logo draw failed"));
    });
    ctx.drawImage(img, x, y, size, size);
  } catch (error) {
    const reason = error instanceof Error ? error.message : "canvas logo draw failed";
    warnWithFallback(reason, onWarning);
  }
}

function drawLogoOnPdf(
  doc: jsPDF,
  assets: BrandingAssets,
  x: number,
  y: number,
  size: number,
  onWarning?: WarningHandler
) {
  try {
    doc.addImage(assets.logoPngDataUrl || assets.logoDataUrl, "PNG", x, y, size, size);
  } catch (error) {
    const reason = error instanceof Error ? error.message : "pdf logo draw failed";
    warnWithFallback(reason, onWarning);
  }
}

export async function drawHeader(
  target: PdfHeaderTarget | CanvasHeaderTarget,
  opts: ExportHeaderOptions,
  onWarning?: WarningHandler
) {
  const assets = await getBrandingAssets(onWarning);
  const header = formatExportHeader(opts);

  if (target.kind === "pdf") {
    const { doc, margin, pageWidth } = target;
    drawLogoOnPdf(doc, assets, margin, margin - 1, 15, onWarning);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(35);
    doc.text(header.titleLeft, margin + 18, margin + 3);
    doc.setFontSize(11);
    doc.setTextColor(30);
    doc.text(header.titleCenter, pageWidth / 2, margin + 3, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(header.titleRight, pageWidth - margin, margin + 3, { align: "right" });
    doc.setFontSize(6.2);
    doc.setTextColor(140);
    doc.text(header.subline, pageWidth / 2, margin + 10.5, { align: "center" });
    doc.setDrawColor(0, 209, 255);
    doc.setLineWidth(0.5);
    doc.line(margin, margin + 12, pageWidth - margin, margin + 12);
    return;
  }

  const { ctx, canvasWidth, marginX } = target;
  await drawLogoOnCanvas(ctx, assets, marginX, 18, 44, onWarning);
  ctx.fillStyle = "#000000";
  ctx.font = "bold 18px Inter, system-ui, sans-serif";
  ctx.textAlign = "left";
  ctx.fillText(header.titleLeft, marginX + 56, 34);
  ctx.font = "bold 24px Inter, system-ui, sans-serif";
  ctx.textAlign = "center";
  ctx.fillText(header.titleCenter, canvasWidth / 2, 32);
  ctx.font = "14px Inter, system-ui, sans-serif";
  ctx.fillStyle = "#555";
  ctx.textAlign = "right";
  ctx.fillText(header.titleRight, canvasWidth - marginX, 34);
  ctx.font = "12px Inter, system-ui, sans-serif";
  ctx.fillStyle = "#777";
  ctx.textAlign = "center";
  ctx.fillText(header.subline, canvasWidth / 2, 88);
  ctx.strokeStyle = "#00d1ff";
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(marginX, 98);
  ctx.lineTo(canvasWidth - marginX, 98);
  ctx.stroke();
}

export function drawFooter(
  target: PdfFooterTarget | CanvasFooterTarget,
  appName = "Wrap Preview"
) {
  if (target.kind === "pdf") {
    const { doc, pageWidth, pageHeight, margin, pageLabel } = target;
    doc.setFontSize(6.5);
    doc.setTextColor(100);
    if (pageLabel) {
      doc.text(pageLabel, pageWidth / 2, pageHeight - 6, { align: "center" });
    }
    doc.text(appName, margin, pageHeight - 6);
    doc.text("© Alan Alves. All rights reserved.", pageWidth - margin, pageHeight - 6, { align: "right" });
    return;
  }

  const { ctx, canvasWidth, canvasHeight, pageLabel } = target;
  ctx.textAlign = "center";
  ctx.font = "11px Inter, system-ui, sans-serif";
  ctx.fillStyle = "#999";
  const footerText = pageLabel
    ? `${appName}  •  ${pageLabel}  •  © Alan Alves. All rights reserved.`
    : `© Alan Alves. All rights reserved.  •  ${appName}`;
  ctx.fillText(footerText, canvasWidth / 2, canvasHeight - 12);
}
